server {
    listen 80;
    client_max_body_size 10M;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ ^/(predict|plants|health|metrics) {
        proxy_pass http://api:5000;
        proxy_set_header Host $host;
        proxy_read_timeout 120s;
    }
}